frontend:
  image:
    repository: null
    tag: latest
    # cmd: ["your_cmd"]
    # args: ["an", "array", "of", "values"]

  # Port to expose on the pod.
  port: 3000

  # Path for health check.
  health: "/"

  # Define extra environment variables for your application
  extraEnv: {}

  url: null

backend:
  image:
    repository: null
    tag: latest
    # cmd: ["your_cmd"]
    # args: ["an", "array", "of", "values"]

  # Port to expose on the pod.
  port: 8080

  # Path for health check.
  health: "/"

  # Define extra environment variables for your application
  extraEnv: {}

  url: null
